Move the selection between the native and Python implementations of lzo and lz4 to dissect.util
fox-it/dissect.squashfs pull request #27
Opened 2024-07-19 12:27 UTC by pyrco

2024-07-19 12:29 UTC, pyrco commented
This PR depends on https://github.com/fox-it/dissect.util/pull/51

2024-07-19 13:22 UTC, Schamper requested changes

2024-07-19 14:25 UTC, pyrco commented on dissect/squashfs/compression.py
> -        return self._module.decompress(data, False, expected)
It should be. Before this change it was already used in a way that expects it to be.

2024-07-25 14:56 UTC, Schamper requested changes

2024-07-25 14:56 UTC, Schamper commented on README.md
> +Unfortunately there is no binary python-lzo wheel for PyPy installations on Windows, so it won't be installed there
```suggestion
Unfortunately there is no binary `python-lzo` wheel for PyPy installations on Windows, so it won't be installed there
```

2024-07-26 10:37 UTC, Schamper submitted a review, later dismissed

2024-07-26 21:32 UTC, Schamper approved these changes

2024-07-29 07:59 UTC, merged